[[plugin]]
id = "soulvice/tailscale"
name = "Tailscale"
version = "1.0.0"
author = "soulvice"
license = "MIT"
icon = "shield"
description = "A minimal Tailscale plugin that shows the current status of tailscale"
min_noctalia = "5.0.0"
tags = ["tailscale" "network"]
