

id = "soulvice/tailscale"
name = "Tailscale"
version = "1.0.3"
min_noctalia = "5.0.0"
author = "soulvice"
license = "MIT"
tags = ["tailscale", "network"]
icon = "sheild"
description = "A minimal Tailscale plugin that shows the current status of tailscale"

[[setting]]
key = "poll_interval"
type = "int"
label = "Poll Interval (ms)"
default = 5000
min = 1000
max = 10000
description = "Refresh interval that tailscale status is called to update the status."

[[setting]]
key = "tailscale_bin"
type = "file"
default = "tailscale"
label = "Tailscale Binary"
description = "Location of the tailscale binary"

[[widget]]
id = "tailscale_bar"
entry = "bar.luau"

[[widget.setting]]
key = "hide_when_disconnected"
type = "bool"
default = false
label = "Hide When Disconnected"
description = "Hide bar widget when tailscale is disconnected."

[[widget.setting]]
key = "show_label"
type = "bool"
label = "Show Data Label"
default = false

[[widget.setting]]
key = "label_content"
type = "select"
default = "none"
label = "Data in label to show"
description = "What date to show in the label next to the icon."
options = [
    { value = "ipaddr",   label = "IP Address" },
    { value = "hostname", label = "Hostname"   },
]
visible_when = { key = "show_label", values = ["true"] }

[[shortcut]]
id = "tailscale_shortcut"
entry = "shortcut.luau"

[[service]]
id = "tailscale_service"
entry = "service.luau"
